### ISSUE TITLE
UnsatisfiedLinkError when launching.

### ISSUE THREAD

**Issue by NemesisMate** [davidB/jme3_ext_assettools#1]
I tried to launch the tools to try: https://github.com/xbuf/blender_io_xbuf, but whatever version I try to use (I've only tried with 0.3.0 and 0.3.3) I get the next exception:

```
mkdir: cannot create directory ‘/home/user/Downloads/jme3_ext_assettools/app/log’: File exists
2016/10/12 10:43:12:301 INFO m.a: ------------------ VM Info ------------------
2016/10/12 10:43:12:308 INFO m.a: -- OS Name: Linux
2016/10/12 10:43:12:309 INFO m.a: -- OS Arch: i386
2016/10/12 10:43:12:309 INFO m.a: -- OS Vers: 4.4.0-38-generic
2016/10/12 10:43:12:309 INFO m.a: -- Java Vers: 1.8.0_20
2016/10/12 10:43:12:309 INFO m.a: -- Java Home: /home/user/Downloads/jme3_ext_assettools/jre
2016/10/12 10:43:12:309 INFO m.a: -- User Name: user
2016/10/12 10:43:12:309 INFO m.a: -- User Home: /home/user
2016/10/12 10:43:12:309 INFO m.a: -- Cur dir: /home/user/Downloads/jme3_ext_assettools
2016/10/12 10:43:12:310 INFO m.a: ---------------------------------------------
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/user/Downloads/jme3_ext_assettools/jre/lib/i386/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1083)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1835)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
        at java.awt.Color.<clinit>(Color.java:275)
        at com.threerings.getdown.data.Application$UpdateInterface.<init>(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.<init>(Unknown Source)
        at com.threerings.getdown.launcher.k.<init>(Unknown Source)
        at com.threerings.getdown.launcher.GetdownApp.main(Unknown Source)
```

**Comment by davidB** [comment]
I didn't updated this project since a long time (is not dead, just it need more love and time).
You don't need it to try xbuf + jme (why do come here).
the libs and sample tool for xbuf + jme are at https://github.com/xbuf/jme3_xbuf
I also provide a pre-build version of the viewer at https://github.com/xbuf/jme3_xbuf/releases

**Comment by NemesisMate** [comment]
The same exception is being thrown by the 0.9.1 version in that releases :S:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/user/Downloads/jme3_xbuf_viewer/jre/lib/i386/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at java.awt.Toolkit$3.run(Toolkit.java:1636)
        at java.awt.Toolkit$3.run(Toolkit.java:1634)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
        at java.awt.Color.<clinit>(Color.java:275)
        at com.threerings.getdown.data.Application$UpdateInterface.<init>(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.<init>(Unknown Source)
        at com.threerings.getdown.launcher.k.<init>(Unknown Source)
        at com.threerings.getdown.launcher.GetdownApp.main(Unknown Source)
```

I'll try to build it from the sources.

**Comment by davidB** [comment]
You can try to run the viewer with your local jre by using the archive
without jre. I guess that provided jre doesn't work on your os.
tbh I never try it on linux i386 (I only have 64bit).

Anyways, a goal of tool/lib remote_viewer is to be used with our own app.

Thanks for the feedback.
